services:
  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    ports:
      - "29092:29092"   # cliente en host
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
      - ALLOW_PLAINTEXT_LISTENER=yes

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on: [kafka]

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    container_name: schema-registry
    ports:
      - "8081:8081"
    environment:
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=kafka:9092
    depends_on: [kafka]

  ksqldb:
    image: confluentinc/ksqldb-server:0.29.0
    container_name: ksqldb
    ports:
      - "8088:8088"
    environment:
      - KSQL_BOOTSTRAP_SERVERS=kafka:9092
      - KSQL_LISTENERS=http://0.0.0.0:8088
      - KSQL_KSQL_SERVICE_ID=ksql_local
      - KSQL_KSQL_STREAMS_AUTO_OFFSET_RESET=earliest
      - KSQL_KSQL_SCHEMA_REGISTRY_URL=http://schema-registry:8081
    depends_on: [kafka, schema-registry]

  ksqldb-cli:
    image: confluentinc/ksqldb-cli:0.29.0
    container_name: ksqldb-cli
    entrypoint: /bin/sh
    tty: true
    depends_on: [ksqldb]

  connect:
    image: confluentinc/cp-kafka-connect:7.6.1
    container_name: connect
    ports:
      - "8083:8083"
    environment:
      - CONNECT_BOOTSTRAP_SERVERS=kafka:9092
      - CONNECT_GROUP_ID=connect
      - CONNECT_CONFIG_STORAGE_TOPIC=_connect_configs
      - CONNECT_OFFSET_STORAGE_TOPIC=_connect_offsets
      - CONNECT_STATUS_STORAGE_TOPIC=_connect_status
      - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1

      # REST listener explícito
      - CONNECT_LISTENERS=http://0.0.0.0:8083
      - CONNECT_REST_ADVERTISED_HOST_NAME=connect
      - CONNECT_REST_ADVERTISED_PORT=8083

      # Converters AVRO + SR
      - CONNECT_KEY_CONVERTER=io.confluent.connect.avro.AvroConverter
      - CONNECT_VALUE_CONVERTER=io.confluent.connect.avro.AvroConverter
      - CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=http://schema-registry:8081

      # Plugins: incluye ambos paths
      - CONNECT_PLUGIN_PATH=/usr/share/java,/usr/share/confluent-hub-components

    # Volumen persistente para que el JDBC quede guardado en el host
    volumes:
      - C:/Users/user/Documents/reto2-kafka/connect-plugins:/usr/share/confluent-hub-components

    depends_on: [kafka, schema-registry]


  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=streaming
    ports:
      - "5432:5432"

  grafana:
    image: grafana/grafana:10.4.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on: [postgres]
